### ISSUE TITLE
Иконка HH и письма выглядит криво

### ISSUE THREAD

**Issue by lichutin** [Artik-Man/artik.me#1]
![image](https://user-images.githubusercontent.com/6536928/56901794-a3174180-6aa1-11e9-835f-c9d9c86a0340.png)

Не выровнены относительно центра

**Comment by Artik-Man** [comment]
ServiceWorker закешировал старую версию сайта на твоем компе. Обнови, используя комбинацию Shift+F5 (Chrome) и дай обратную связь по проблеме

**Comment by lichutin** [comment]
@Artik-Man но ведь ты не будешь просить юзеров сбросить кэш) как решается проблема инвалидации кэша с сервис-воркерами при деплое новой версии?

**Comment by Artik-Man** [comment]
@lichutin  В текущей версии обновлён сервис воркер. Теперь, когда появляются обновления, они догружаются в фоновом режиме и при следующей перезагрузке страницы, ты увидишь обновленный сайт.
